version: '3.8'

services:
  web:
    build:
      context: .
      target: deps
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/esim_db
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=esim_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 