version: '3.8'

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=esim_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 