[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y python3-minimal python3-pip && pip3 install --no-warn-script-location -r webhooks/requirements.txt && npm install --omit=dev && npm run build"

[deploy]
startCommand = "python3 webhooks/main.py & npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
PORT = "3000"
NEXT_PUBLIC_API_URL = "https://www.globlinksolution.com"
NEXT_PUBLIC_PAYMENT_WEBHOOK_URL = "https://globlinkesimwebsite-production.up.railway.app/api/webhooks/payment"
NEXT_PUBLIC_ESIM_WEBHOOK_URL = "https://globlinkesimwebsite-production.up.railway.app/api/webhooks/esim"
WEBHOOK_PORT = "3001" 