[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y python3-minimal python3-pip && pip3 install --no-warn-script-location -r webhooks/requirements.txt && npm install --omit=dev && npm run build"

[deploy]
startCommand = "cd webhooks && python3 main.py & cd .. && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
PORT = "3000"
NEXT_PUBLIC_API_URL = "https://www.globlinksolution.com"
NEXT_PUBLIC_PAYMENT_WEBHOOK_URL = "https://globlinkesimwebsite-production.up.railway.app/api/webhooks/payment"
NEXT_PUBLIC_ESIM_WEBHOOK_URL = "https://globlinkesimwebsite-production.up.railway.app/api/webhooks/esim"
NEXT_PUBLIC_PAYMENT_EVENTS_URL = "https://globlinkesimwebsite-production.up.railway.app/api/webhooks/payment/last-events"
NEXT_PUBLIC_ESIM_EVENTS_URL = "https://globlinkesimwebsite-production.up.railway.app/api/webhooks/esim/last-events"
WEBHOOK_PORT = "3001" 