[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[cron]
schedule = "*/5 * * * *"
command = "curl -X GET -H \"Authorization: Bearer ${CRON_SECRET}\" ${RAILWAY_PUBLIC_DOMAIN}/api/cron/process-queue" 