[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y python3-minimal python3-pip && pip3 install --no-warn-script-location -r requirements.txt"

[deploy]
startCommand = "python3 main.py"
healthcheckPath = "/payment/last-events"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "3001" 